name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pring getting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Good Bye"
      
